spring:
  application.name: gateway 
  cloud:
    gateway:
      default-filters:
      - PrefixPath=/
      routes:
      #=========================
      - id: register
        uri: lb://register
        predicates:
        - Path=/register/**
        filters:
        - StripPrefix=1
        - name: CircuitBreaker
          args:
            name: register-fallback
            fallbackUri: forward:/fallback/register
      #=========================
      - id: login
        uri: lb://login
        predicates:
        - Path=/login/**
        filters:
        - StripPrefix=1
